// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfileFormController from "./profile_form_controller"
application.register("profile-form", ProfileFormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TiltController from "./tilt_controller"
application.register("tiltable", TiltController)

import ScrollController from "./scroll_controller"
application.register("scroller", ScrollController)
