// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownRevealController from "./dropdown_reveal_controller"
application.register("dropdown-reveal", DropdownRevealController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfileFormController from "./profile_form_controller"
application.register("profile-form", ProfileFormController)
