meta_product_name: "Crewsin"
meta_title: "Crewsin - Sailing Docs Simplified"
meta_description: "Gather the neccesary documents for you and your crew and send them to the charter agency simply and conveniently "
meta_image: "login.png" # should exist in `app/assets/images/`
